#!/usr/bin/env bash
echo build latest version and copy that to the bin directory

progfile=$0
if test -L "$progfile"; then
  progfile=$(readlink "$progfile")
fi
progdir=$(dirname "$progfile")/..
cd "$progdir" || exit 1
mvn -B clean test || exit 1
mvn -B -Dmaven.test.skip.exec -DskipITs -Ddocker.skip.run install || exit 1

echo Copying to bin
mv -f bin/co-developer-gpt-engine.jar bin/co-developer-gpt-engine.bak.jar
mv $progdir/target/co-developer-gpt-engine-*.jar bin/co-developer-gpt-engine.jar
ls -l bin
