#!/usr/bin/env bash

# if test ! -f $(dirname $0)/target/developersChatGPTtoolbenchPlugin-*.jar; then
set -xv
progfile=$0
if test -L "$progfile"; then
  progfile=$(readlink "$progfile")
fi
progdir=$(dirname "$progfile")
mvn -B -f $progdir/pom.xml install
echo
echo
# fi

java -jar $progdir/target/developersChatGPTtoolbenchPlugin-*.jar "$@"
